apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 4.2.0
    authorization:
      type: simple
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    - name: external
      port: 9094
      type: nodeport
      tls: false
      authentication:
        type: scram-sha-512
      configuration:
        bootstrap:
          nodePort: 30092
        preferredNodePortAddressType: InternalDNS
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker-node-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 2
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
      - id: 1
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
      - id: 2
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
  resources:
    requests:
      memory: 2Gi
      cpu: "1"
    limits:
      memory: 4Gi
      cpu: "2"
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker-rtsp-server
                - worker-sentry-rejoin
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controller-node-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: ephemeral
  resources:
    requests:
      memory: 1Gi
      cpu: "0.5"
    limits:
      memory: 2Gi
      cpu: "1"
  jvmOptions:
    -Xms: 1g
    -Xmx: 1g
