MAKEFLAGS += --always-make



# ---------------------------------------------- NETWORK ----------------------------------------------
create_network:
	docker network create --subnet=172.11.10.0/24 --gateway=172.11.10.1 --driver=bridge demo
