KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="external-user"
    password="mdL0Q9gKAANuglBV8KaGvPYS6NihQP5u"
    user_external-user="mdL0Q9gKAANuglBV8KaGvPYS6NihQP5u";
};
